# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

services:
  ###########################
  # Database
  ###########################
  db: # "db" est le DNS => Dans le code source, remplacer localhost par db
    container_name: postgres_ecommerce_dev
    restart: always
    build: ./docker/postgres/
    ports:
      - "6666:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: projet-e-commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
  #######################################
  # Apache - Front UI (client and admin)
  #######################################
  httpd:
    container_name: apache_ecommerce_dev
    restart: always
    build: ./docker/apache
    ports:
      - "1080:80"
    volumes:
      - ./docker/apache/vhost/:/usr/local/apache2/conf/vhosts
      - ./docker/apache/certs/nextoo.crt:/usr/local/apache2/conf/server.crt
      - ./docker/apache/certs/nextoo.key:/usr/local/apache2/conf/server.key
      - ../e-commerce-ui:/var/www/e-commerce-ui
      - ../e-commerce-ui-admin:/var/www/e-commerce-ui-admin
  ###########################
  # Java Backend
  ###########################
  java:
    container_name: java_ecommerce_dev
    build: ./docker/java/
    ports:
      - "8888:8888"
    volumes:
      - ../e-commerce:/e-commerce
    depends_on:
      - db
#TODO    command: []
###########################
# SonarQube
###########################
#  sonarqube:
#    container_name: sonarqube_ecommerce
#    build: ./docker/sonarqube/
#    ports:
#      - "9000:9000"
#    environment:
#      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
#      - SONARQUBE_JDBC_USERNAME=postgres
#      - SONARQUBE_JDBC_PASSWORD=azerty
#    volumes:
#      - ./docker/sonarqube/sonarqube_conf/:/opt/sonarqube/conf
#      - ./docker/sonarqube/sonarqube_data/:/opt/sonarqube/data
#      - ./docker/sonarqube/sonarqube_extensions/:/opt/sonarqube/extensions
#      - ./docker/sonarqube/sonarqube_bundled-plugins/:/opt/sonarqube/lib/bundled-plugins
