# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

volumes:
    database_tuto:
        driver: local
services:
###########################
# Database
###########################
  db: # "db" est le DNS => Dans le code source, remplacer localhost par db
    container_name: postgres_ecommerce_dev
    restart: always
    build: ./docker/postgres/
    ports:
      - "6666:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: projet-e-commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
#######################################
# Apache - Front UI (client and admin)
#######################################
  httpd:
    container_name: apache_ecommerce_dev
    restart: always
    build: ./docker/apache
    ports:
      - "80:1080"
      - "443:1443"
    volumes:
      - ./docker/apache/vhost/:/usr/local/apache2/conf/vhosts
      - ./docker/apache/certs/nextoo.crt:/usr/local/apache2/conf/server.crt
      - ./docker/apache/certs/nextoo.key:/usr/local/apache2/conf/server.key
    volumes_from:
      - data
###########################
# Data
###########################
  data:
    container_name: data_ecommerce_dev
    build: ./docker/data/
    volumes:
      - ./../e-commerce-ui:/var/www/e-commerce-ui
      - ./../e-commerce-ui-admin:/var/www/e-commerce-ui-admin
      - ./../e-commerce:/var/www/e-commerce
###########################
# Java Backend
###########################
  java:
    container_name: java_ecommerce_dev
    build: ./docker/java/
    expose:
      - "9000"
    volumes_from:
      - data
###########################
# SonarQube
###########################
  sonarqube:
    container_name: sonarqube_ecommerce
    build: ./docker/sonarqube/
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=azerty
    volumes:
      - ./docker/sonarqube/sonarqube_conf/:/opt/sonarqube/conf
      - ./docker/sonarqube/sonarqube_data/:/opt/sonarqube/data
      - ./docker/sonarqube/sonarqube_extensions/:/opt/sonarqube/extensions
      - ./docker/sonarqube/sonarqube_bundled-plugins/:/opt/sonarqube/lib/bundled-plugins
###########################
# Adminer
###########################
  adminer:
    container_name: adminer_ecommerce
    build: ./docker/adminer/
    ports:
      - "2002:80"
